### ISSUE TITLE
Link to documentation conda is not working

### ISSUE THREAD

**Issue by stijnvanhoey** [jorisvandenbossche/course-python-data#49]
on slides

**Comment by stijnvanhoey** [comment]
https://docs.conda.io/projects/conda/en/latest/user-guide/index.html seems to work fine

**Comment by jorisvandenbossche** [comment]
On the slides http://conda.pydata.org/docs/using/index.html is not working, fixing

**Comment by jorisvandenbossche** [comment]
Ah, in course-python-data that's already updated ..
