### ISSUE TITLE
rename/drop in exercise bike count not yet tackled as notebook 06 cleaning is not yet given

### ISSUE THREAD

**Issue by stijnvanhoey** [jorisvandenbossche/course-python-data#51]
could just be removed on this location

**Comment by stijnvanhoey** [comment]
I checked the updated version in https://github.com/jorisvandenbossche/course-python-data/pull/69 and I do think we should keep the drop/rename as part of the case study and just refer to the notebook 6. Otherwise, the preprocessing of the raw data is too extensive to call it a case study. @jorisvandenbossche, ok?

**Comment by jorisvandenbossche** [comment]
Yep, sounds fine.
