### ISSUE TITLE
Typo in notebook case1_bike_count

### ISSUE THREAD

**Issue by flamerond** [jorisvandenbossche/course-python-data#53]
When plotting the daily patterns at the end of the case study, in the text it says the following:

"So the daily pattern is clearly different for both directions. In the morning more people go north, in the evening more people go south. The morning peak is also more condensed."

However, in the morning more people actually go south (not north) towards Gent, and in the evening more people go north (towards Mariakerke). I think you just switched north and south.

**Comment by stijnvanhoey** [comment]
Thanks a lot for the input. Fixed by https://github.com/jorisvandenbossche/course-python-data/pull/63 for the next course
