### ISSUE TITLE
Visualization landscape examples not working

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/course-python-data#76]
Last time I tried this (at date of writing), several things were not working:

- the plotly plot doesn't show up (although their jupyterlab extension is installed)
- the datashader example isn't interactive (zooming in just enlarges the pixels, it doesn't recalculate them)

**Comment by stijnvanhoey** [comment]
> the plotly plot doesn't show up (although their jupyterlab extension is installed)

I checked in a fresh install of all packages in mamba and I can not reproduce this error. Charts are shown in jupyter (I did got message about 'recommend to build' which works fine)
![image](https://github.com/jorisvandenbossche/course-python-data/assets/754862/7c9bce8d-ec03-4979-bcd6-4f247509b150)

> the datashader example isn't interactive (zooming in just enlarges the pixels, it doesn't recalculate them)

Although I had to rerun some cells and nothing was shonw first, once the chart is created, it did work succesfully

![image](https://github.com/jorisvandenbossche/course-python-data/assets/754862/7cea06d3-25e2-4211-9891-2af3711ca2f2)

**Comment by jorisvandenbossche** [comment]
With a clean environment with the latest versions installed today, everything is working fine indeed
